version: '3'
services:
  db:
    container_name: rebirth
    image: mongo:4.4.1
    environment:
      - MONGO_INITDB_DATABASE=rebirth
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017-27019:27017-27019'
