version: '3'
services:
  db:
    container_name: rebirth_db
    image: postgres:10.7
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=rebirth
      - POSTGRES_DB=rebirth_db
    ports:
      - '5432:5432'
